name: 'PowerShell Module Cache'
description: 'Cache modules from the PowerShell Gallery'
inputs:
  modules-to-install:  # id of input
    description: 'Modules to install or cache'
    required: true
outputs:
  installed-modules: 
    description: "List of modules"
    value: ${{ steps.all-modules.outputs.list-of-modules }}
runs:
  using: "composite"
  steps: 
    - run: echo Installing and caching ${{ inputs.modules-to-install }}.
      shell: bash
    - run: ${{ github.action_path }}/cache.ps1 -Module ${{ inputs.modules-to-install }}
      shell: pwsh
    - id: all-modules
      run: Write-Output "::set-output name=list-of-modules::$(Get-ChildItem /)"
      shell: pwsh