name: 'Hello World'
description: 'Greet someone'
inputs:
  modules-to-install:  # id of input
    description: 'Who to greet'
    required: true
outputs:
  list-of-all-installed-modules: 
    description: "List of modules"
    value: ${{ steps.all-modules.outputs.list-of-modules }}
runs:
  using: "composite"
  steps: 
    - run: echo Hello ${{ inputs.modules-to-install }}.
      shell: bash
    - id: all-modules
      run: echo "::set-output name=list-of-modules::$(Get-Module)"
      shell: pwsh
    - run: ${{ github.action_path }}/goodbye.ps1
      shell: pwsh