name: 'Hello World'
description: 'Greet someone'
inputs:
  modules-to-install:  # id of input
    description: 'The comma separated list of the modules to install'
    required: true
outputs:
  installed-modules: 
    description: "All installed modules"
    value: ${{ steps.installed-modules-list.outputs.installed-modules }}
runs:
  using: "composite"
  steps:
    - run: echo Hello ${{ inputs.modules-to-install }}.
      shell: pwsh
    - id: installed-modules-list
      run: echo "::set-output name=installed-modules::$(Get-Module)"
      shell: pwsh
    - run: ${{ github.action_path }}/goodbye.ps1
      shell: pwsh