name: 'PowerShell Module Cache'
description: 'Cache modules from the PowerShell Gallery'
inputs:
  modules-to-install:
    description: 'Modules to install or cache'
    required: true
outputs:
  paths: 
    description: "Output paths"
    value: ${{ steps.psoutput.outputs.paths }}
  paths2: 
    description: "Output paths"
    value: ${{ steps.psoutput.outputs.paths2 }}
  current-modules: 
    description: "List of modules"
    value: ${{ steps.bashoutput.outputs.list-of-modules }}
runs:
  using: "composite"
  steps: 
    - run: echo Finding install path for ${{ inputs.modules-to-install }}.
      shell: bash
    - id: psoutput
      shell: pwsh
      run: |
        Write-Output "::set-output name=paths::$((Get-ChildItem /tmp) -join ', ')"
        Write-Output "::set-output name=paths2::$(${{ github.action_path }}/cache.ps1 -Module ${{ inputs.modules-to-install }})"
    - id: bashoutput
      run: echo "::set-output name=list-of-modules::${{ inputs.modules-to-install }}"
      shell: bash