name: 'PowerShell Module Cache'
description: 'Cache modules from the PowerShell Gallery'
inputs:
  modules-to-install:
    description: 'Modules to install or cache'
    required: true
outputs:
  paths: 
    description: "Output paths"
    value: ${{ steps.psoutput.outputs.paths }}
  needed: 
    description: "Output paths"
    value: ${{ steps.psoutput.outputs.needed }}
  current-modules: 
    description: "List of modules"
    value: ${{ steps.bashoutput.outputs.list-of-modules }}
runs:
  using: "composite"
  steps: 
    - id: intro
      shell: bash
      run: echo Finding install path for ${{ inputs.modules-to-install }}.
    - id: psoutput
      shell: pwsh
      run: |
        Write-Output "::set-output name=paths::$(${{ github.action_path }}/cache.ps1 -Module ${{ inputs.modules-to-install }})"
        Write-Output "::set-output name=needed::$(${{ github.action_path }}/cache.ps1 -NeededOnly -Module ${{ inputs.modules-to-install }})"
    - id: bashoutput
      shell: bash
      run: echo "::set-output name=list-of-modules::${{ inputs.modules-to-install }}"