name: 'PowerShell Module Cache'
description: 'Cache modules from the PowerShell Gallery'
inputs:
  modules-to-install:
    description: 'Modules to install or cache'
    required: true
outputs:
  modules: 
    description: "List of modules"
    value: ${{ steps.all-modules.outputs.list-of-modules }}
  output-paths: 
    description: "Output paths"
    value: ${{ steps.install-paths.outputs.output-path }}
runs:
  using: "composite"
  steps: 
    - run: echo Installing and caching ${{ inputs.modules-to-install }}.
      shell: bash
    - id: perform-install
      run:  ${{ github.action_path }}/cache.ps1 -Module ${{ inputs.modules-to-install }}
      shell: pwsh
    - id: install-paths
      shell: pwsh
      run: |
        Import-Module PSFramework, Pester
        Write-Output "::set-output name=output-path::$((Get-Module PSFramework, Pester | Select -ExpandProperty Path) -join ', ')"
    - id: all-modules
      run: echo "::set-output name=list-of-modules::${{ inputs.modules-to-install }}"
      shell: bash