@{
 MustDefineAtLeastOneModule="You must define at least one module to be cached, either via the 'module-to-cache' parameter or the 'module-to-cache-prerelease' parameter."
 MustDefineAtLeastOneShell="You must define at least one shell, 'powershell' or 'pwsh' or both."
 MustBeAnAuthorizedShell="The 'Shell' parameter contains an empty string or a shell name which is not supported '{0}'. Allowed shell names are 'pwsh' and 'powershell'."
 EmptyModuleName="A module name is empty for '{0}'."
 MissingRequiredVersion="The required version is not specified for '{0}'."
 InvalidVersionNumberSyntax="The syntax of the version '{0}' is invalid for '{1}'."
 ModuleCannotContainPrerelease="A module name into 'module-to-cache' cannot contain a prerelease version '{0}'."
 ModuleMustContainPrerelease="A module name into 'module-to-cache-prerelease' must contain a prerelease version '{0}'."
 ImmutableCacheCannotContainUpdatableInformation="An immutable cache cannot contain updatable cache information ('::') into 'module-to-cache' or 'module-to-cache-prerelease' (see '{0}')."
 UpdatableCacheMustContainUpdatableInformation="An updatable cache must contain cache information ('::') into 'module-to-cache' or 'module-to-cache-prerelease' (see '{0}')."
 UpdatableModuleCannotContainVersionInformation="An updatable module must not specify a version number '{0}'."
 UnknownModuleName="Find-Package: No match was found for the specified search criteria and the updatable module name '{0}' (repositories '{1}')."
 ValidationMustBeHashtable="Repository credentials must be saved in a hashtable [System.Collections.Hashtable]"
 ValidationMustContainAtLeastOneEntry="The repositories credentials hashtable is empty, it must contain at least one entry."
 ValidationWrongItemType="The objects contained in the repository credentials hashtable must be of type [Key=String,Value=PScredential]."
 ValidationInvalidKey="The repositories credentials hashtable can not contains a key which is an empty string."
 ValidationUnknownRepository="A PSRepository name referenced in the repository credentials hashtable does not exist or cannot be found."
 EmptyCredentialFileName="The name of the file containing the credential is empty, has the environment variable 'PSModuleCacheCredentialFileName' been created?"
 }
