
name: UbuntuCheckErrorInstallModulesOnPowershell
on:
  workflow_dispatch:

jobs:
  UbuntuCheckErrorInstallModulesOnPowershell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set required PowerShell modules
        id: psmodulecache
        uses: ./
        with:
          modules-to-cache: dbatools, SpeculationControl,PoshRSJob
          shell: powershell
          updatable: "false"
          prefixidentifier: "true"

      - name: Show that the Action works on powershell
        shell: powershell
        run: |
           Write-Warning "PSVersionTable `r`n$($PSVersionTable.GetEnumerator()|Out-String -width 512)"
           'PoshRSJob', 'dbatools', 'SpeculationControl'|
           Foreach {
              Import-Module $_
              Write-host "$_ '$(Get-Module $_|Select-Object Name,Version,RepositorySourceLocation)'"
           }
