name: UbuntuInstallModulesOnPsCore
on:
  workflow_dispatch:

jobs:
  InstallModulesOnPsCore:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.5.0

      - name: Set required PowerShell modules
        id: psmodulecache
        uses: ./
        with:
          modules-to-cache: PoshRSJob, dbatools, SpeculationControl
          shell: pwsh
          updatable: "false"
          prefixidentifier: "true"

      - name: Show that the Action works on pwsh
        shell: pwsh
        run: |
          'PoshRSJob', 'dbatools', 'SpeculationControl' |
           foreach {
              Import-Module $_
              Write-Host "$_ '$(Get-Module $_ | Select-Object Name, Version, RepositorySourceLocation)'"
          }
